server:
  port: 8081

spring:
  jackson:
    time-zone: Asia/Seoul

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: haertz
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: ${GOOGLE_SCOPE}

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 1

  kakao:
    pay:
      kakaoAdminKey: ${KAKAOADMIN_KEY}
      approveUrl: ${APPROVE_URL}
      cancelUrl: ${CANCEL_URL}
      failUrl: ${FAIL_URL}

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always

jwt:
  secret-key: ${JWT_SECRET}
  access-token-exp: ${JWT_ACCESS_EXP}
  refresh-token-exp: ${JWT_REFRESH_EXP}